<?php
namespace LiteSpeed\Cache\Helper;

use LiteSpeed\Cache\Config\ObjConfig;
use PrestaShop\PrestaShop\Adapter\Configuration\PhpParameters;

/**
 * Activates / deactivates the Redis object cache driver in PrestaShop.
 *
 *  1. Writes (or removes) config/litespeed_redis.php inside the module dir
 *     — the connection file read by CacheRedis at bootstrap time.
 *  2. Patches parameters.php via PrestaShop's own PhpParameters class
 *     — sets ps_caching='CacheRedis' and ps_cache_enable=true/false.
 *  3. Regenerates the PS class index.
 *
 * The actual class loading is handled by the Cache.php override which
 * loads the module's vendor/autoload.php when needed.
 */
class ObjectCacheActivator
{
    /**
     * Enable Redis as PS object cache driver.
     */
    public static function enable(array $cfg): bool
    {
        if (!self::writeConnectionConfig($cfg)) {
            return false;
        }

        if (!self::setParameters('CacheRedis', true)) {
            return false;
        }

        self::regenerateClassIndex();

        return true;
    }

    /**
     * Disable Redis object cache and revert to no caching.
     */
    public static function disable(): bool
    {
        self::removeConnectionConfig();

        $result = self::setParameters('CacheMemcache', false);

        self::regenerateClassIndex();

        return $result;
    }

    /**
     * Called on module uninstall: leave PS in a clean state.
     */
    public static function disableIfActive(): void
    {
        if (!defined('_PS_CACHING_SYSTEM_') || _PS_CACHING_SYSTEM_ !== 'CacheRedis') {
            return;
        }
        if (!defined('_PS_CACHE_ENABLED_') || !_PS_CACHE_ENABLED_) {
            return;
        }
        self::disable();
    }

    // -------------------------------------------------------------------------

    private static function regenerateClassIndex(): void
    {
        try {
            \PrestaShop\Autoload\PrestashopAutoload::getInstance()->generateIndex();
        } catch (\Exception $e) {
            // Silently ignore — index will be rebuilt on next cache clear
        }
    }

    private static function configFilePath(): string
    {
        $dir = defined('_PS_MODULE_DIR_') ? _PS_MODULE_DIR_ : '';
        return $dir . 'litespeedcache/config/litespeed_redis.php';
    }

    private static function parametersFilePath(): string
    {
        $root = defined('_PS_ROOT_DIR_') ? rtrim(_PS_ROOT_DIR_, '/') : '';
        return $root . '/app/config/parameters.php';
    }

    private static function writeConnectionConfig(array $cfg): bool
    {
        $data = [
            'host'     => (string) ($cfg[ObjConfig::OBJ_HOST]       ?? 'localhost'),
            'port'     => (int)    ($cfg[ObjConfig::OBJ_PORT]       ?? 6379),
            'password' => (string) ($cfg[ObjConfig::OBJ_PASSWORD]   ?? ''),
            'db'       => (int)    ($cfg[ObjConfig::OBJ_REDIS_DB]   ?? 0),
            'ttl'      => (int)    ($cfg[ObjConfig::OBJ_TTL]        ?? 360),
            'prefix'   => defined('_DB_PREFIX_') ? _DB_PREFIX_ . 'lsc_' : 'ps_lsc_',
        ];

        $php = "<?php\n// Auto-generated by LiteSpeedCache — do not edit manually.\nreturn "
             . var_export($data, true) . ";\n";

        return file_put_contents(self::configFilePath(), $php) !== false;
    }

    private static function removeConnectionConfig(): void
    {
        $file = self::configFilePath();
        if (is_file($file)) {
            @unlink($file);
        }
    }

    private static function setParameters(string $driver, bool $enabled): bool
    {
        $file = self::parametersFilePath();
        if (!is_file($file) || !is_writable($file)) {
            return false;
        }

        try {
            $params = new PhpParameters($file);
            $params->setProperty('parameters.ps_caching', $driver);
            $params->setProperty('parameters.ps_cache_enable', $enabled);
            return $params->saveConfiguration();
        } catch (\Exception $e) {
            return false;
        }
    }
}
