admin_litespeedcache_manage:
    path: /litespeedcache/manage
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ManageController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheManage
        _legacy_link: AdminLiteSpeedCacheManage

admin_litespeedcache_presets:
    path: /litespeedcache/presets
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\PresetsController::indexAction'
        _legacy_controller: AdminLiteSpeedCachePresets
        _legacy_link: AdminLiteSpeedCachePresets

admin_litespeedcache_config:
    path: /litespeedcache/config
    methods: [GET]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ConfigController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheConfig
        _legacy_link: AdminLiteSpeedCacheConfig

admin_litespeedcache_cdn:
    path: /litespeedcache/cdn
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\CdnController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheCdn
        _legacy_link: AdminLiteSpeedCacheCdn

admin_litespeedcache_objectcache:
    path: /litespeedcache/cache/object
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ObjController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheObjectCache
        _legacy_link: AdminLiteSpeedCacheObjectCache

admin_litespeedcache_exclusions:
    path: /litespeedcache/cache/exclusions
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ExclusionsController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheExclusions
        _legacy_link: AdminLiteSpeedCacheExclusions

admin_litespeedcache_stats:
    path: /litespeedcache/stats
    methods: [GET]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\StatsController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheStats
        _legacy_link: AdminLiteSpeedCacheStats


admin_litespeedcache_warmup:
    path: /litespeedcache/warmup
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\WarmupController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheWarmup
        _legacy_link: AdminLiteSpeedCacheWarmup

admin_litespeedcache_warmup_save_state:
    path: /litespeedcache/warmup/save-state
    methods: [POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\WarmupController::saveStateAction'
        _legacy_controller: AdminLiteSpeedCacheWarmup

admin_litespeedcache_warmup_urls:
    path: /litespeedcache/warmup/urls
    methods: [POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\WarmupController::urlsAction'
        _legacy_controller: AdminLiteSpeedCacheWarmup

admin_litespeedcache_warmup_crawl:
    path: /litespeedcache/warmup/crawl
    methods: [POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\WarmupController::crawlAction'
        _legacy_controller: AdminLiteSpeedCacheWarmup

admin_litespeedcache_warmup_load_check:
    path: /litespeedcache/warmup/load-check
    methods: [POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\WarmupController::loadCheckAction'
        _legacy_controller: AdminLiteSpeedCacheWarmup

admin_litespeedcache_tools:
    path: /litespeedcache/tools
    methods: [GET]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::redirectAction'
        _legacy_controller: AdminLiteSpeedCacheTools
        _legacy_link: AdminLiteSpeedCacheTools

admin_litespeedcache_tools_purge:
    path: /litespeedcache/tools/purge
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheToolsPurge
        tab: purge

admin_litespeedcache_tools_import_export:
    path: /litespeedcache/tools/import-export
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheToolsImportExport
        tab: import-export

admin_litespeedcache_tools_htaccess:
    path: /litespeedcache/tools/htaccess
    methods: [GET]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheToolsHtaccess
        tab: htaccess

admin_litespeedcache_tools_report:
    path: /litespeedcache/tools/report
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheToolsReport
        tab: report

admin_litespeedcache_tools_debug:
    path: /litespeedcache/tools/debug
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheToolsDebug
        tab: debug

admin_litespeedcache_tools_logs:
    path: /litespeedcache/tools/logs
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheToolsLogs
        tab: logs

admin_litespeedcache_tools_access_log:
    path: /litespeedcache/tools/access-log
    methods: [GET]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::accessLogAction'
        _legacy_controller: AdminLiteSpeedCacheToolsLogs

admin_litespeedcache_tools_updates:
    path: /litespeedcache/tools/updates
    methods: [GET]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheToolsUpdates
        tab: updates

admin_litespeedcache_tools_update_apply:
    path: /litespeedcache/tools/updates/apply
    methods: [POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::updateAction'
        _legacy_controller: AdminLiteSpeedCacheToolsUpdates

admin_litespeedcache_tools_update_rollback:
    path: /litespeedcache/tools/updates/rollback
    methods: [POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::updateAction'
        _legacy_controller: AdminLiteSpeedCacheToolsUpdates

admin_litespeedcache_tools_update_delete_backup:
    path: /litespeedcache/tools/updates/delete-backup
    methods: [POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\ToolsController::updateAction'
        _legacy_controller: AdminLiteSpeedCacheToolsUpdates

admin_litespeedcache_database:
    path: /litespeedcache/database
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\DatabaseController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheDatabase
        _legacy_link: AdminLiteSpeedCacheDatabase

admin_litespeedcache_cache:
    path: /litespeedcache/cache
    methods: [GET]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\CacheController::redirectAction'
        _legacy_controller: AdminLiteSpeedCacheCache
        _legacy_link: AdminLiteSpeedCacheCache

admin_litespeedcache_cache_settings:
    path: /litespeedcache/cache/settings
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\CacheController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheCacheSettings

admin_litespeedcache_ttl:
    path: /litespeedcache/cache/ttl
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\TtlController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheTtl

admin_litespeedcache_advanced:
    path: /litespeedcache/cache/advanced
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\AdvancedController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheAdvanced

admin_litespeedcache_esi:
    path: /litespeedcache/cache/esi
    methods: [GET]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\EsiController::indexAction'
        _legacy_controller: AdminLiteSpeedCacheEsi
        _legacy_link: AdminLiteSpeedCacheCustomize

admin_litespeedcache_esi_add:
    path: /litespeedcache/cache/esi/add
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\EsiController::addAction'
        _legacy_controller: AdminLiteSpeedCacheEsi

admin_litespeedcache_esi_edit:
    path: /litespeedcache/cache/esi/edit/{id}
    methods: [GET, POST]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\EsiController::editAction'
        _legacy_controller: AdminLiteSpeedCacheEsi

admin_litespeedcache_esi_view:
    path: /litespeedcache/cache/esi/view/{id}
    methods: [GET]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\EsiController::viewAction'
        _legacy_controller: AdminLiteSpeedCacheEsi

admin_litespeedcache_esi_delete:
    path: /litespeedcache/cache/esi/delete/{id}
    methods: [GET]
    defaults:
        _controller: 'LiteSpeed\Cache\Controller\Admin\EsiController::deleteAction'
        _legacy_controller: AdminLiteSpeedCacheEsi
