<?php
/**
 * LiteSpeed Cache for PrestaShop — Redis object cache driver.
 *
 * Namespaced class loaded by the Cache.php override when
 * _PS_CACHING_SYSTEM_ === 'CacheRedis'. The override loads the module's
 * vendor/autoload.php which registers this PSR-4 namespace.
 *
 * Connection settings come from config/litespeed_redis.php (generated by
 * ObjController on save) so this class has zero dependency on Configuration
 * or Db at construction time, avoiding circular bootstrap issues.
 */

namespace LiteSpeed\Cache\Cache;

class CacheRedis extends \CacheCore
{
    /** @var \Redis|null */
    protected ?\Redis $redis = null;

    protected bool $is_connected = false;
    protected int  $default_ttl  = 360;
    protected string $prefix     = '';

    /** @var array In-memory cache for current request */
    private array $localCache = [];

    public function __construct()
    {
        $this->connect();
    }

    public function __destruct()
    {
        if ($this->is_connected && $this->redis) {
            try { $this->redis->close(); } catch (\Exception $e) {}
        }
    }

    // -------------------------------------------------------------------------
    // Connection
    // -------------------------------------------------------------------------

    protected function connect(): void
    {
        if (!extension_loaded('redis')) {
            return;
        }

        if (!defined('_PS_CACHE_ENABLED_') || !_PS_CACHE_ENABLED_) {
            return;
        }

        $configFile = defined('_PS_MODULE_DIR_')
            ? _PS_MODULE_DIR_ . 'litespeedcache/config/litespeed_redis.php'
            : '';

        if (!$configFile || !is_file($configFile)) {
            return;
        }

        $cfg = @include $configFile;
        if (!is_array($cfg)) {
            return;
        }

        $host = (string) ($cfg['host']     ?? 'localhost');
        $port = (int)    ($cfg['port']     ?? 6379);
        $pass = (string) ($cfg['password'] ?? '');
        $db   = (int)    ($cfg['db']       ?? 0);
        $this->default_ttl = (int)    ($cfg['ttl']    ?? 360);
        $this->prefix      = (string) ($cfg['prefix'] ?? '');

        try {
            $this->redis = new \Redis();
            if (!$this->redis->connect($host, $port, 2.0)) {
                return;
            }
            if ($pass !== '') {
                $this->redis->auth($pass);
            }
            if ($db > 0) {
                $this->redis->select($db);
            }
            $this->redis->setOption(\Redis::OPT_SERIALIZER, \Redis::SERIALIZER_PHP);
            $this->is_connected = true;
        } catch (\Exception $e) {
            $this->is_connected = false;
            $this->redis        = null;
        }
    }

    public function isConnected(): bool
    {
        return $this->is_connected;
    }

    // -------------------------------------------------------------------------
    // Key helpers
    // -------------------------------------------------------------------------

    protected function k(string $key): string
    {
        return $this->prefix . $key;
    }

    // -------------------------------------------------------------------------
    // High-level public methods — bypass parent $keys[] index so hits persist
    // across requests (same pattern as CacheMemcached in PS core).
    // -------------------------------------------------------------------------

    public function set($key, $value, $ttl = 0)
    {
        if (!$this->is_connected) {
            return false;
        }
        if (is_null($value)) {
            return false;
        }
        return $this->_set($key, $value, $ttl);
    }

    public function get($key)
    {
        if (!$this->is_connected) {
            return false;
        }
        return $this->_get($key);
    }

    public function exists($key)
    {
        if (!$this->is_connected) {
            return false;
        }
        return $this->_exists($key);
    }

    public function delete($key)
    {
        if (!$this->is_connected) {
            return false;
        }

        if ($key === '*') {
            return $this->flush();
        }

        if (strpos($key, '*') === false) {
            $this->_delete($key);
            return true;
        }

        // Wildcard: use SCAN with pattern
        $pattern = $this->k($key);
        $cursor  = null;
        do {
            $found = $this->redis->scan($cursor, $pattern, 200);
            if (is_array($found) && $found) {
                $this->redis->del(...$found);
            }
        } while ($cursor !== 0);

        return true;
    }

    // -------------------------------------------------------------------------
    // Abstract implementations (CacheCore)
    // -------------------------------------------------------------------------

    protected function _set($key, $value, $ttl = 0)
    {
        if (!$this->is_connected) {
            return false;
        }

        $ttl    = $ttl > 0 ? (int) $ttl : $this->default_ttl;
        $newKey = $this->k($key);

        try {
            if ($ttl > 0) {
                $result = $this->redis->setex($newKey, $ttl, $value);
            } else {
                $result = $this->redis->set($newKey, $value);
            }

            if ($result) {
                $this->localCache[$newKey] = $value;
            }

            return (bool) $result;
        } catch (\Exception $e) {
            return false;
        }
    }

    protected function _get($key)
    {
        if (!$this->is_connected) {
            return false;
        }

        $newKey = $this->k($key);

        if (isset($this->localCache[$newKey])) {
            return $this->localCache[$newKey];
        }

        try {
            $result = $this->redis->get($newKey);

            if ($result !== false) {
                $this->localCache[$newKey] = $result;
            }

            return $result;
        } catch (\Exception $e) {
            return false;
        }
    }

    protected function _exists($key)
    {
        if (!$this->is_connected) {
            return false;
        }

        $newKey = $this->k($key);

        if (isset($this->localCache[$newKey])) {
            return true;
        }

        return (bool) $this->redis->exists($newKey);
    }

    protected function _delete($key)
    {
        if (!$this->is_connected) {
            return false;
        }

        $newKey = $this->k($key);
        unset($this->localCache[$newKey]);

        try {
            return (bool) $this->redis->del($newKey);
        } catch (\Exception $e) {
            return false;
        }
    }

    protected function _writeKeys()
    {
        return true;
    }

    public function flush()
    {
        if (!$this->is_connected) {
            return false;
        }

        $this->localCache = [];

        if ($this->prefix === '') {
            return (bool) $this->redis->flushDB();
        }

        // Prefixed mode: only delete our keys via SCAN
        $cursor = null;
        do {
            $found = $this->redis->scan($cursor, $this->prefix . '*', 500);
            if (is_array($found) && $found) {
                $this->redis->del(...$found);
            }
        } while ($cursor !== 0);

        return true;
    }
}
